### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by szepeviktor**
## Description

Found two misspellings.

## Motivation and context

Show what `typos` can do.

## Checklist:

- [x] I have read the **[CONTRIBUTING](CONTRIBUTING.md)** document.
- [x] My pull request addresses exactly one patch/feature.
- [ ] I have created a branch for this patch/feature.
- [ ] I have added tests to cover my changes.
- [ ] If my change requires a change to the documentation, I have updated it accordingly.

### CODE REVIEW

**Comment by szepeviktor** [comment]
There is a test called `testFindWithMisspelingHandler` (with 1 `l`)

**Comment by tigitz** [comment]
Good catch, thanks !

> ➕ There is a test called testFindWithMisspelingHandler (with 1 l)

Quite ironic for a spellchecking lib :sweat_smile:

**Comment by szepeviktor** [comment]
Glad to contribute.

**Comment by szepeviktor** [comment]
You find tools for caring about byte in this repository https://github.com/szepeviktor/byte-level-care/tree/master/.github/workflows

**Pull request merged**
